defaults:
  - baseline
  - _self_

experiment_name: resnet50_baseline

data:
  image_size: 256
  batch_size: 16
  num_workers: 16
  use_self_augmentation: false
  pairs_per_person_in_batch: 4
  augmentations:
    training: []
    validation: []
    testing: []

model:
  backbone:
    name: resnet50
    resnet50:
      source: torchvision.models # use local for custom architectures
      pretrained: true
      weights_source: "results/weights/age_resnet50.pth" # use torch for official weights or path for custom weights;
  wrapper:
    name: const_offset
    const_offset:
      factor: 0.5

optimizer:
  lr: 1e-5
  betas: [0.99, 0.9995]
  weight_decay: 1e-4
  scheduler_gamma: 0.995

training:
  use_full_dataset: false
  num_epochs: 20
  patience: 15
  checkpoint_interval: 5
  accumulation_steps: 1


loss:
  type: l1


log:
  tensorboard: true
