defaults:
  - baseline
  - _self_

experiment_name: resnet50_const_offset

data:
  image_size: 256
  batch_size: 32
  num_workers: 16
  use_self_augmentation: true
  pairs_per_person_in_batch: 4
  augmentations:
    training: []
    validation: []
    testing: []

model:
  backbone:
    name: resnet50
    resnet50:
      source: torchvision.models # use local for custom architectures
      pretrained: true
      weights_source: "weights/age_resnet50.pth" # use torch for official weights or path for custom weights;
  wrapper:
    name: const_offset

optimizer:
  lr: 1e-6
  betas: [0.99, 0.9995]
  weight_decay: 1e-3
  scheduler_gamma: 0.995

training:
  use_full_dataset: false
  num_epochs: 20
  patience: 10
  checkpoint_interval: 5
  accumulation_steps: 1


loss:
  type: l1


log:
  tensorboard: true
